### PR TITLE
Add option to hide project in status success

### PR DESCRIPTION
**Pull request by JBertaux**

### CODE REVIEW

**Comment by timoschwarzer** [comment]
Hi! Thank you very much for this PR. I think this is a good addition! :)

**Comment by timoschwarzer** [comment]
I'd prefer something more flexible like `showJobsNameOnlyOn` though.

e.g.

```yaml
showProjectOnlyOn:
  - canceled
  - failed
  - pending
  - running
  - skipped
  - manual
```

Can you change your PR to reflect that behavior? :)

**Comment by JBertaux** [comment]
I made the change ;)

**Comment by timoschwarzer** [comment]
Thank you very much! :)

**Pull request merged**
