### PR TITLE
json documentation for CONFIGURATION.md

### PR DESCRIPTION
**Pull request by fredmorin**
I attempted to use the project and ran into a problem figuring out how to properly configure the dashboard.
This merge request is an attempt to fix the documentation issue.

### CODE REVIEW

**Comment by timoschwarzer** [comment]
It was JSON some months ago. Please ensure you're running the latest version :)

**Comment by fredmorin** [comment]
Using the docker image.

**Comment by fredmorin** [comment]
Should probably delete the json example file

**Comment by timoschwarzer** [comment]
> Using the docker image from docker hub with the latest tag.
Then you are most probably not using the latest image and need to pull.

> Should probably delete the json example file
There is no json example file. There is only the YAML-configuration documentation in `CONFIGURATION.md`.

**Comment by fredmorin** [comment]
see: https://github.com/timoschwarzer/gitlab-monitor/pull/133

**Pull request closed without merging**
