### PR TITLE
Fixing Docker, prompting the token

### PR DESCRIPTION
**Pull request by bonndan**
This PR improves docker usage in production and prompts for the required parameters if they are not present in the url query.

### CODE REVIEW

**Comment by timoschwarzer** [comment]
Thank you! :)
I'll review the commits in some minutes...

**Comment by timoschwarzer** [comment]
Some small things:
- Could you put the http-server command line into the package.json as a script, please?
- And Gitlab → GitLab

Thank you :)

**Comment by bonndan** [comment]
- I have no experience with yarn so far. Does it handle SIGINT and the like similar to direct calls of http-server? Otherwise it's preferable to keep the current CMD.
- Where is the typo?

**Comment by timoschwarzer** [comment]
- Yes, just add a script to the `package.json`:
  ```
  ...
  "scripts": {
    "serve": "http-server ./dist"
  }
  ...
  ```
- It's in the `prompt()` calls :wink:

**Comment by bonndan** [comment]
Done. One thing I have to check: in the docker file http-server serves "/" while the script is supposed to serve "/dist". We have the docker version running and working properly, how can that work?

**Comment by timoschwarzer** [comment]
Hi @bonndan!

That's actually a question that I have, too, and I have no idea why that's working for you. It shouldn't.

Thank you for the PR! Really appreciated :)

**Comment by timoschwarzer** [comment]
Okay, I investigated a bit:
When you run http-server without `./dist`, it serves the index.html from the repository root (https://github.com/timoschwarzer/gitlab-monitor/blob/master/index.html). That file serves as a debug entry HTML for HMR to work. Since it references `./dist/build.js`, it worked. But it's better to serve the built index.html from `./dist` like it does now.

Again, thanks for the PR! :)

**Comment by bonndan** [comment]
:+1: 
Could you change the Dockerfile CMD in your repo? I'd be glad to use it.

**Pull request merged**
