### PR TITLE
Fixed current branch running

### LINKED ISSUE #1: BUG: In the project view it always shows the default branch even though something else is running
It seems that the project view always shows the default branch, no matter which one is running

[line with default branch](https://github.com/timoschwarzer/gitlab-monitor/blob/master/src/components/project-card.vue#L8)

It should show the branch that is actually running.
It seems that the info is on the pipeline object in the `ref` property

### PR DESCRIPTION
**Pull request by mribichich**
Moved the `branch div` inside the pipeline, in order to show the current branch running.

This will fix #1 for now

Later it can be improve to support multi pipelines with #2

### CODE REVIEW

**Comment by mribichich** [comment]
It looks like this now:

image

**Comment by timoschwarzer** [comment]
How does it look when there are two pipelines running from two branches?

**Comment by mribichich** [comment]
I didn't do that yet. I only fixed the current branch running. 
Thats why is safe to merge this, it doesn't break anything

I was going to do the multi pipeline tomorrow and show you the possibilities.

**Comment by mribichich** [comment]
It's a first step to multi pipelines

**Comment by timoschwarzer** [comment]
That sounds awesome! Thank you! :smile:

**Pull request merged**
