### PR TITLE
Support rate limit using axios-rate-limit module towards gitlab

### PR DESCRIPTION
**Pull request by norrs**

### CODE REVIEW

**Comment by norrs** [comment]
For an organization that has >1000 repositories, we need to rate limit ourselves.

**Comment by timoschwarzer** [comment]
I don't think rate limiting is a good approach here because we don't really have control over the requests anymore.
I'd rather vote for a polling interval multiplier.

**Comment by norrs** [comment]
The polling interval multiplier doesn't help us, but you are free to reject the PR. We will merge locally in our private fork. 

Currently there is a huge problem that the whole application does a ton of API requests, like 10 000 etc in just a few minutes .. 
This was a quick fix for us while we will be looking into how to redo parts of the application to do less API calls.

**Comment by timoschwarzer** [comment]
Why doesn't the multiplier help here?

If I understand correctly, it will discard/stall requests with rate limiting.

The best option would be a websocket server which receives web hook calls from GitLab. Still not sure how to do that. Best option would be that you provide an access token and GitLab Monitor configures the web hooks by itself via the API.

**Comment by norrs** [comment]
> Why doesn't the multiplier help here?

Personal preference, easier to configure. 
Thought maybe colleague had tested with multiplier, but he says no I just figured out.
At least we saw it fires a lot of requests at once if you have a lot of projects, so this helped us. 

> If I understand correctly, it will discard/stall requests with rate limiting.

AFAIK it doesn't discard requests, but it will stall/queue up requests according to rateLimit configuration.

> The best option would be a websocket server which receives web hook calls from GitLab. Still not sure > how to do that. Best option would be that you provide an access token and GitLab Monitor configures > the web hooks by itself via the API.

This requires a significant rewrite I believe, not something I intend to do ATM.

**Comment by norrs** [comment]
If you want, I can put it under a feature flag to only make it enabled via a feature flag in the config , to give end users the option to use it if they want.

You can also reject the proposal and we'll simply maintain it internally in our fork.

**Comment by norrs** [comment]
In matter of rejecting I still suggest you to cherry pick https://github.com/timoschwarzer/gitlab-monitor/pull/74/commits/78ccc6c72db9d9499adba2136bf5b50a421dc4aa

**Comment by timoschwarzer** [comment]
> it will stall/queue up requests according to rateLimit configuration.

The problem is that the queue will get longer and longer over time, so it's just a temporary solution which will fail if you intend to run gitlab-monitor 24/7.



> In matter of rejecting I still suggest you to cherry pick [78ccc6c](https://github.com/timoschwarzer/gitlab-monitor/commit/78ccc6c72db9d9499adba2136bf5b50a421dc4aa)

Thanks!

**Comment by martijnjanssen** [comment]
Some solution of rate-limiting/request spreading would definitely be helpful, or maybe an option to not retrieve all individual pipeline steps and just the stages and display those.

**Pull request closed without merging**
